<style type="text/css">

* {
    padding: 1px;
    margin: 1px;
} 
html {min-width: 1000px; /* Mindestbreite verhindert Anzeigefehler in modernen Browsern */
   max-width: 1300px;}
body {
background: #fff;
font-family: Verdana, Arial, Helvetica, sans-serif;
font-size: 12px;
line-height: 18px;
color: #333333;

}

img { border: none; }
a { color: #57626a; text-decoration: none; }
a:hover { text-decoration: underline; color : #000; }

#wrap {
margin: 0 auto;
width: 800px;
}

#header { 
padding: 10px;
}
#header h1 {
font-size: 26px;
font-weight: 100;
letter-spacing: 3px;
padding: 12px 0 5px 10px;
white-space: nowrap;
}
#header h1 a {
color: #57626a;
text-decoration: none;
}
#header h1 a:hover {
color: #57626a;
text-decoration: none;
}
#header h2 {
color: #ccc;
font-size: 15px;
font-weight: 100;
padding: 0 0 0 11px;
letter-spacing: -1px;
line-height: 12px;
}

#menu {
margin: 5px;
font size= 8px;
padding: 5px;
height: 50px;
line-height: 20px;
background: #57626a;
text-transform: uppercase;
}
#menu ul {
padding: 0px 3px;
list-style-type: none;
}
#menu ul li {
display: block;
float: left;
}
#menu ul li a {
color: #eee;
padding: 5px;
text-decoration: none;
font-weight: 100;
font-size: 14px;
letter-spacing: 0px;
}
#menu ul li a:hover {
color: #eee;
text-decoration: underline;
}

#Inhalt {
padding: 10px 0px;
}

.right {
width: 568px;
float: right;
text-align: justify;
}
.right h2 {
color: #FF4800;
font-size: 20px;
letter-spacing: -3px;
font-weight: 100;
padding : 10px 0 15px 0;
}

.left {
width: 150px;
float: left;
padding: 10px;
border-right: 1px solid #bbb;
font-size: 12px;
}
.left ul {
list-style-type: square;
padding: 5px 10px 10px 20px;
color: #57626a;
}
.left h2 {
height: 30px;
font-size: 14px;
color: #666;
line-height: 30px;
font-weight: 600;
}
.left a { text-decoration: none }

#footer {
background: #eee;
border-top: 3px solid #57626a;
margin-top: 20px;
text-align: center;
color: #333;
font-size: 11px;
padding: 10px;
}
table #festgelegt{
text-align: center;
width:1300px;}


</style>
<div>
<div id="header">
<h1 nowrap="nowrap"><P STYLE="margin-bottom: 0cm" nowrap="nowrap"><FONT SIZE=7 STYLE="font-size: 40pt"><FONT COLOR="#ff6309">O</FONT><FONT COLOR="#ff0000"><SPAN STYLE="background: transparent">e</SPAN></FONT>-<FONT COLOR="#000080">B</FONT><FONT COLOR="#ffff00">O</FONT><FONT COLOR="#3deb3d">O</FONT><FONT COLOR="#ff6309">KS</FONT><FONT COLOR="#cccccc">Oe-BOOKSOe-BOOKS</FONT></FONT></P><h1>
<h2>media trading</h2> 
</div>

<div id="menu" nowrap="nowrap">
<ul>
<li><a href="angebot.php">Angebote</a><br><a href="suchanzeigen.php">Suchanzeigen</a></li>
<li><a href="maske.php">Angebot/Sucheanzeige erstellen</a></li>
<li><a href="angebotnachhilfestunden.php">Angebote Nachhilfestunden</a><br><a href="suchenachhilfestunden.php">Suchanzeigen Nachhilfestunden</a></li>
<li><a href="Nachhilfestundenmaske.php">Nachhilfe anbieten/suchen</a></li>
<li><a href="nutzerprofil.php">Nutzerprofil</a></li>
<li><a href="FAQ2.php">Anleitung</a></li>
</ul>
</div>
</div>
